# Generated by Django 5.0.14 on 2026-03-09 14:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scanned_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("invalid", "Invalid"),
                            ("alredy used", "Alredy Used"),
                            ("not active", "Not Active"),
                        ],
                        max_length=20,
                    ),
                ),
                ("meta", models.JSONField(default=dict)),
                (
                    "checker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="orders.ticket",
                    ),
                ),
            ],
        ),
    ]
