# Generated by Django 6.0.2 on 2026-03-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_rename_create_at_payment_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="yookassa", max_length=32)),
                ("dedupe_key", models.CharField(max_length=32, unique=True)),
                ("event_type", models.CharField(max_length=64)),
                ("object_id", models.CharField(blank=True, max_length=128)),
                ("signature_ok", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("raw_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
